<?php /*** @var $block Monicavelez\Blog\Block\PostList */ ?>

<h1><?php echo __('Latest Blog Posts') ?></h1>
<ul class="blog-post-list">
    <?php /** @var $post \Monicavelez\Blog\Model\Post */?>

    <?php foreach($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="<?php echo $post->getUrlKey()?>"><?php echo $post->getTitle() ?></a>
            </h3>

            <div class="blog-post-item">
                <?php echo $post->getContent() ?>
            </div>

            <div class="blog-post-item-meta">
                <strong>
                    <?php echo __('Created at:') ?>
                    <?php echo $post->getCreationTime() ?>
                </strong>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
